--1) 과목번호, 과목이름, 교수번호, 교수이름을 담을 수 있는 변수들을 선언하고 
--   유기화학 과목의 과목번호, 과목이름, 교수번호, 교수이름을 출력하세요.
DECLARE
	CNO VARCHAR2(10);
	CNAME VARCHAR2(20);
	PNO VARCHAR(10);
	PNAME VARCHAR2(20);
BEGIN
		SELECT C.CNO, C.CNAME, P.PNO, P.PNAME
			INTO CNO, CNAME, PNO, PNAME
			FROM COURSE C
			JOIN PROFESSOR P
			  ON C.PNO = P.PNO
			WHERE C.CNAME = '유기화학';
		DBMS_OUTPUT.PUT_LINE(CNO || CNAME || PNO || PNAME);
END;

--2) 위 데이터들을 레코드로 선언하고 출력하세요.
DECLARE
	TYPE COURSE_PROFESSOR IS RECORD(
		CNO VARCHAR2(10),
		CNAME VARCHAR2(20),
		PNO VARCHAR(10),
		PNAME VARCHAR2(20)
	);

	CP COURSE_PROFESSOR;
BEGIN
	SELECT C.CNO, C.CNAME, P.PNO, P.PNAME
		INTO CP
		FROM COURSE C
		JOIN PROFESSOR P
		  ON C.PNO = P.PNO
		WHERE C.CNAME = '유기화학';
	DBMS_OUTPUT.PUT_LINE(CP.CNO || CP.CNAME || CP.PNO || CP.PNAME);
END;
