--1) 송강 교수가 강의하는 과목을 검색한다
SELECT C.CNO 
	, C.CNAME 
	FROM COURSE C
	JOIN PROFESSOR PF
	  ON C.PNO = PF.PNO
	 WHERE PF.PNAME = '송강';

--2) 화학 관련 과목을 강의하는 교수의 명단을 검색한다
SELECT C.CNO 
	, C.CNAME
	, PF.PNAME 
	FROM COURSE C
	JOIN PROFESSOR PF
	  ON C.PNO = PF.PNO
	 WHERE C.CNAME LIKE '%화학%';

--3) 학점이 2학점인 과목과 이를 강의하는 교수를 검색한다
SELECT C.CNO 
	, C.CNAME
	, PF.PNAME 
	FROM COURSE C
	JOIN PROFESSOR PF
	  ON C.PNO = PF.PNO
	 WHERE C.ST_NUM = 2;

--4) 화학과 교수가 강의하는 과목을 검색한다
SELECT C.CNO 
	, C.CNAME
	, PF.PNAME 
	FROM COURSE C
	JOIN PROFESSOR PF
	  ON C.PNO = PF.PNO
	 WHERE PF."SECTION" = '화학';

--5) 화학과 1학년 학생의 기말고사 성적을 검색한다
SELECT SC."RESULT" 
	FROM STUDENT ST
	JOIN SCORE SC
	  ON ST.SNO = SC.SNO 
	WHERE ST.MAJOR = '화학'
	  AND ST.SYEAR = 1;

--6) 일반화학 과목의 기말고사 점수를 검색한다
SELECT SC."RESULT" 
	FROM SCORE SC
	JOIN COURSE C
	  ON C.CNO = SC.CNO
	WHERE C.CNAME = '일반화학';

--7) 화학과 1학년 학생의 일반화학 기말고사 점수를 검색한다
SELECT SC."RESULT" 
	FROM STUDENT ST
	JOIN SCORE SC
	  ON ST.SNO = SC.SNO 
	JOIN COURSE C
	  ON SC.CNO = C.CNO 
	WHERE ST.MAJOR = '화학'
	  AND ST.SYEAR = 1
	  AND C.CNAME = '일반화학';

--8) 화학과 1학년 학생이 수강하는 과목을 검색한다
SELECT DISTINCT  SC.CNO 
	, C.CNAME 
	FROM STUDENT ST
	JOIN SCORE SC
	  ON ST.SNO = SC.SNO 
	JOIN COURSE C
	  ON SC.CNO = C.CNO 
	WHERE ST.MAJOR = '화학'
	  AND ST.SYEAR = 1;

--9) 유기화학 과목의 평가점수가 F인 학생의 명단을 검색한다
SELECT ST.SNAME 
	FROM STUDENT ST
	JOIN SCORE SC
	  ON ST.SNO = SC.SNO 
	JOIN COURSE C
	  ON SC.CNO = C.CNO 
	JOIN SCGRADE SCG
	  ON SC."RESULT" BETWEEN SCG.LOSCORE AND SCG.HISCORE 
	WHERE C.CNAME = '유기화학'
	  AND SCG.GRADE = 'F';

