--1) 학생중에 동명이인을 검색한다
SELECT ST1.*
	FROM STUDENT ST1
	JOIN STUDENT ST2
	  ON ST1.SNAME = ST2.SNAME 
	 AND ST1.SNO != ST2.SNO
	 ORDER BY ST1.SNAME;

--2) 전체 교수 명단과 교수가 담당하는 과목의 이름을 학과 순으로 검색한다
SELECT PF.SECTION
	, PF.PNAME
	, C.CNAME
	FROM PROFESSOR PF
	LEFT JOIN COURSE C
	  ON PF.PNO  = C.PNO
	ORDER BY PF."SECTION" ;

--3) 이번 학기 등록된 모든 과목과 담당 교수를 학점 순으로 검색한다
SELECT C.CNO 
	, C.CNAME 
	, PF.PNAME 
	, C.ST_NUM 
	FROM COURSE C
	RIGHT JOIN PROFESSOR PF
	  ON C.PNO = PF.PNO 
	ORDER BY C.ST_NUM; 
